In [1]:
import numpy as np

def compute_mean_and_variance(arr):
    mean = np.mean(arr)
    variance = np.var(arr)
    return mean, variance

# Example usage
N = 10  # Dimensionality of the feature vector
sample_vector = np.random.rand(N)  # Generating a random sample vector
mean, variance = compute_mean_and_variance(sample_vector)

print("Sample Vector:", sample_vector)
print("Mean of the sample vector:", mean)
print("Variance of the sample vector:", variance)


Sample Vector: [0.78551987 0.33888289 0.44389318 0.41388987 0.03936443 0.5166779
 0.52110932 0.15224988 0.37068782 0.89936061]
Mean of the sample vector: 0.4481635751260276
Variance of the sample vector: 0.060122266883397946


In [2]:
import numpy as np

def compute_covariance(vector1, vector2):
    covariance = np.cov(vector1, vector2)
    return covariance[0, 1]  # Extracting the covariance value between vector1 and vector2

# Example usage
M = 5  # Dimensionality of the feature vectors
sample_vector1 = np.random.rand(1, M)  # Generating a random sample vector 1
sample_vector2 = np.random.rand(1, M)  # Generating a random sample vector 2
covariance = compute_covariance(sample_vector1, sample_vector2)

print("Sample Vector 1:", sample_vector1)
print("Sample Vector 2:", sample_vector2)
print("Covariance between the two vectors:", covariance)


Sample Vector 1: [[0.32851831 0.2350699  0.99109961 0.83253394 0.0543707 ]]
Sample Vector 2: [[0.0442182  0.43602637 0.63435099 0.57377438 0.17039644]]
Covariance between the two vectors: 0.08125235086472213


In [3]:
import numpy as np

def compute_correlation(vector1, vector2):
    correlation = np.corrcoef(vector1, vector2)
    return correlation[0, 1]  # Extracting the correlation value between vector1 and vector2

# Example usage
N = 8  # Dimensionality of the vectors
vector1 = np.random.rand(1, N)  # Generating a random vector 1
vector2 = np.random.rand(1, N)  # Generating a random vector 2
correlation = compute_correlation(vector1, vector2)

print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Correlation between the two vectors:", correlation)


Vector 1: [[0.20657852 0.8855176  0.17863312 0.00566857 0.84153409 0.48822268
  0.72795196 0.8255093 ]]
Vector 2: [[0.63772381 0.82781449 0.47907014 0.86941766 0.31287737 0.39750128
  0.10445334 0.60957152]]
Correlation between the two vectors: -0.3343813706331778


In [4]:
import numpy as np

def compute_covariance_matrix(data_matrix):
    covariance_matrix = np.cov(data_matrix)
    return covariance_matrix

def compute_correlation_matrix(data_matrix):
    correlation_matrix = np.corrcoef(data_matrix)
    return correlation_matrix

# Example usage
M = 3  # Dimensionality of the feature vector
N = 5  # Number of samples
data_matrix = np.random.rand(M, N)  # Generating a random data matrix

covariance_matrix = compute_covariance_matrix(data_matrix)
correlation_matrix = compute_correlation_matrix(data_matrix)

print("Data Matrix:")
print(data_matrix)
print("\nCovariance Matrix:")
print(covariance_matrix)
print("\nCorrelation Matrix:")
print(correlation_matrix)


Data Matrix:
[[0.3202182  0.20481669 0.85285836 0.85016359 0.6663282 ]
 [0.39645335 0.85176315 0.45701165 0.56129468 0.06597469]
 [0.30575352 0.96281515 0.38613561 0.72228336 0.20952507]]

Covariance Matrix:
[[ 0.09078385 -0.03447575 -0.02979346]
 [-0.03447575  0.0807077   0.08260155]
 [-0.02979346  0.08260155  0.09929584]]

Correlation Matrix:
[[ 1.         -0.40276517 -0.31379864]
 [-0.40276517  1.          0.92270993]
 [-0.31379864  0.92270993  1.        ]]
